// SpeculationTree - Tree data structure for tree-based speculative decoding
//
// The tree represents multiple candidate token sequences generated by the draft model.
// Each node stores a token and its parent index, allowing efficient tree traversal.
// During verification, the target model processes all nodes with tree attention mask.

#include "llm_internal.h"
#include <queue>
#include <algorithm>

namespace granite {

int SpeculationTree::add_node(int32_t token, int parent_idx, float log_prob) {
    int idx = static_cast<int>(nodes_.size());
    Node node;
    node.token = token;
    node.parent_idx = parent_idx;
    node.log_prob = log_prob;

    if (parent_idx < 0) {
        node.depth = 0;
    } else {
        node.depth = nodes_[parent_idx].depth + 1;
        nodes_[parent_idx].children.push_back(idx);
    }

    nodes_.push_back(node);
    return idx;
}

std::vector<int> SpeculationTree::get_leaves() const {
    std::vector<int> leaves;
    for (size_t i = 0; i < nodes_.size(); i++) {
        if (nodes_[i].children.empty()) {
            leaves.push_back(static_cast<int>(i));
        }
    }
    return leaves;
}

std::vector<int> SpeculationTree::get_path(int node_idx) const {
    std::vector<int> path;
    int current = node_idx;
    while (current >= 0) {
        path.push_back(current);
        current = nodes_[current].parent_idx;
    }
    std::reverse(path.begin(), path.end());
    return path;
}

std::vector<int> SpeculationTree::get_parent_indices() const {
    std::vector<int> parents;
    parents.reserve(nodes_.size());
    for (const auto& node : nodes_) {
        parents.push_back(node.parent_idx);
    }
    return parents;
}

std::vector<int32_t> SpeculationTree::flatten_tokens() const {
    // BFS order to maintain parent-before-child ordering
    std::vector<int32_t> tokens;
    tokens.reserve(nodes_.size());

    if (nodes_.empty()) return tokens;

    std::queue<int> queue;
    queue.push(0);  // Start from root

    while (!queue.empty()) {
        int idx = queue.front();
        queue.pop();

        tokens.push_back(nodes_[idx].token);

        for (int child : nodes_[idx].children) {
            queue.push(child);
        }
    }

    return tokens;
}

std::vector<int32_t> SpeculationTree::find_accepted_path(
    const std::vector<int32_t>& target_choices
) const {
    if (nodes_.empty() || target_choices.empty()) {
        return {};
    }

    // Find the longest accepted path from root
    // A node is accepted if its token matches the target's choice at that position

    std::vector<int32_t> best_path;
    std::vector<int32_t> current_path;

    // DFS to find longest accepted path
    std::function<void(int, int)> dfs = [&](int node_idx, int target_pos) {
        if (node_idx < 0 || target_pos >= static_cast<int>(target_choices.size())) {
            // Check if current path is longest
            if (current_path.size() > best_path.size()) {
                best_path = current_path;
            }
            return;
        }

        const Node& node = nodes_[node_idx];

        // Check if this node's token matches target's choice
        if (node.token == target_choices[target_pos]) {
            // Accept this token
            current_path.push_back(node.token);

            if (node.children.empty()) {
                // Leaf node - check if best path
                if (current_path.size() > best_path.size()) {
                    best_path = current_path;
                }
            } else {
                // Continue down each child branch
                for (int child : node.children) {
                    dfs(child, target_pos + 1);
                }
            }

            current_path.pop_back();
        } else {
            // Mismatch - this path ends here
            // But we can still accept the target's choice as the final token
            current_path.push_back(target_choices[target_pos]);
            if (current_path.size() > best_path.size()) {
                best_path = current_path;
            }
            current_path.pop_back();
        }
    };

    // Start DFS from root
    dfs(0, 0);

    return best_path;
}

void SpeculationTree::build(int width, int depth) {
    // This is a placeholder - actual tree building happens in SpeculativeRunner
    // which has access to the draft model for token generation
    (void)width;
    (void)depth;
}

}  // namespace granite
